spring.application.name=backend

server.port=${PORT:8080}

spring.datasource.url=jdbc:mariadb://${MYSQLHOST}:${MYSQLPORT:3306}/${MYSQLDATABASE}?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.id.new_generator_mappings=false
app.seed.enabled=${APP_SEED_ENABLED:true}
brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=dailystore6879@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=dailystore6879@gmail.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
